# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiAUg9_1L4OwO7Jx9pRva02zqIKay1_L
"""

def kasallik_tashxisi(belgi):
  if belgi == "1-semestr":
     return "falsafa, ingliz tili, dasturlash, dinshunoslik, xisob, jismoniy tarbiya, fizika"
  elif belgi == "2-semestr":
    return "xorijiy til, dasturlash, akademik yozuv, differensial tenglamalar, jismoniy tarbiya, fizika, diskret tuzilmalar, tarix"
  elif belgi == "3-semestr":
    return "kiberxavfsizlik asoslari, malumotlar tuzilmasi, elektronika, kompyuterni tashkil etish, suniy intelekt asoslari, maxsus kurs"
  else:
    return "Dekanatga murojaat qiling"
belgi = input("semestrni kiriting")
natija = kasallik_tashxisi(belgi)
print(natija)